.\"
.\" @(#) dbbeauty.1 1.2  03/03/06 10:27:25
.\"
.TH DBBEAUTY 1 "dbbeauty 1.2"
.SH NAME
dbbeauty \- 4GL program beautifier
.SH SYNOPSIS
dbbeauty [file...]
.SH DESCRIPTION
.I Dbbeauty
reads 4GL programs either from "file"
or from standard input and writes them on standard output with
keyword capitalization and indention that displays the structure
of the code.
.SH NOTES
.I Dbbeauty
only converts keywords to upper case at this time. The next major
release of
.I dbbeauty
will support indentation.
.SH SUPPORT
Send bug reports to Dave Snyder <dave@snide.com>
